language: ruby
rvm:
- 2.0.0
services:
- mongodb
- redis-server
- elasticsearch
before_script:
- rake db:mongoid:create_indexes
notifications:
  campfire:
    rooms:
    - secure: |-
        eEuzoYFXLPeIMt+zHGzZp6XCvbfxRDe8FA3kVwrNRB0zoOktPRZXD9O8ng2z
        x2Yg8C7i1unstuW0bjPvwphpdxJOTFSxliw6P4Xk1Y9HnTYQqqUbDat/zL9c
        AyjYezuRQgYFSBP2BgNZ2RL9RiLSyLQBWhcHGB0yBS6rsheKWbk=
    on_success: never
    on_failure: always
  webhooks: http://cfa-project-monitor.herokuapp.com/projects/f4e235b6-734e-4d63-a19b-32426335c047/status
env:
  matrix:
    secure: SyAQm64busWPLwPPdpebaH3QIaK7acP8j7eIj449kI+KYSkTEj5G+ir/Nu1z0XLGv50vmezdg8FsKBe32Bi5c5f1I5rRLsTI9K/lN10OYh6ZzERoTTsypjx+s9xQ1NRPzamMGEpcxG2iOU/n2KU3CPW4BPIp9dpmhUFZ3Obk71Q=
